# Custom Language File for Launcher Customizer

[ejs.app]
title = "YT Clan"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/YT_Clan"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/YT_Clan"
supportLink = "https://github.com/CustomLauncherLab/YT_Clan/issues"

[ejs.welcome]
welcomeHeader = "YT Clan"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."